# This is a basic workflow to help you get started with Actions

name: CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "This is the ${{ github.BASE_REF }} branch."

      - name: Run a multi-line script
        run: |
          echo "The value of THING is ${{ vars.ENVIRONMENT_STAGE }}"
